import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ColorSchemeScript } from "@mantine/core";
import { theme } from "../../theme";
import { MantineProvider } from "@mantine/core";

import "./globals.css";
import "@mantine/core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <head>
        <meta
          name='viewport'
          content='minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no'
        />
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider
          theme={theme}
          withCssVariables
          defaultColorScheme='auto'
        >
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
